version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ${PWD}/Dockerfile
    command: /bin/bash
    volumes:
      - ${PWD}/data:/home/kwy8791/data
      - ${PWD}/conf/.ssh:/home/kwy8791/.ssh
    stdin_open: true
    tty: true
